{
  den.aspects.home.cargo = {
    config,
    pkgs,
    ...
  }: {
    homeManager = {home, ...}: let
      # Ref: https://github.com/phip1611/nixos-configs/blob/main/common/modules/user-env/env/cargo.nix
      # List of binaries to create a symlink to in `~/.cargo/bin`.
      # From my testing, adding "cargo" and "rustc" should be enough, but better
      # be safe.
      cargoSymlinkBins = [
        "cargo"
        "cargo-clippy"
        "rustc"
        "rustdoc"
        "rustfmt"
        "rustup"
      ];

      # Function that creates a list of cargo symlinks for the home-manager.
      createCargoBinSymlinks = mkOutOfStoreSymlink: bins:
        builtins.foldl'
        (acc: bin:
          {
            ".cargo/bin/${bin}".source = mkOutOfStoreSymlink "/etc/profiles/per-user/${home.username}/bin/${bin}";
          }
          // acc)
        {} # accumulator
        
        bins;

      dummyCargoEnvFile = pkgs.writeText "dummy-cargo-env-file.sh" ''
        # Dummy cargo env file generated by NixOS/home-manager.
        # This is only here so that scripts that expect this standard path to be
        # available don't fail. One example are the scripts in the cloud-hypervisor
        # repository, which source this file.
      '';
    in {
      home = {
        file =
          # Ref: https://github.com/phip1611/nixos-configs/blob/main/common/modules/user-env/env/cargo.nix
          createCargoBinSymlinks config.lib.file.mkOutOfStoreSymlink cargoSymlinkBins
          // {
            ".cargo/config.toml".source = ./config.toml;
            ".cargo/env".source = dummyCargoEnvFile;
          };
        sessionPath = ["/home/${home.username}/.cargo/bin"];
      };
    };
  };
}
