repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-added-large-files
  - id: check-yaml
    args:
    - "--allow-multiple-documents"
    additional_dependencies: [ ruamel_yaml ]
  - id: end-of-file-fixer
    exclude: '^(.+\.svg|HpSetup.txt)$'
  - id: trailing-whitespace
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: check-toml
  - id: check-vcs-permalinks
  - id: mixed-line-ending
    exclude: '^(HpSetup.txt)$'
  - id: check-json
  - id: pretty-format-json
    args:
      - "--autofix"
- repo: https://github.com/kamadorueda/alejandra
  rev: 3.0.0
  hooks:
  - id: alejandra-system
- repo: https://github.com/astro/deadnix
  rev: v1.2.1
  hooks:
  - id: deadnix
  # TODO: revert to main project when this is merged
  # https://github.com/oppiliappan/statix/pull/81
- repo: https://github.com/Matthieu-LAURENT39/statix/
  rev: pre-commit
  hooks:
  - id: statix-fix
