repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-added-large-files
  - id: check-yaml
    args:
    - "--allow-multiple-documents"
    additional_dependencies: [ ruamel_yaml ]
  - id: end-of-file-fixer
    exclude: '^(.+\.svg|HpSetup.txt)$'
  - id: trailing-whitespace
    exclude: '^.+\.nix$'
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: check-toml
  - id: check-vcs-permalinks
  - id: mixed-line-ending
    exclude: '^(HpSetup.txt)$'
  - id: check-json
  - id: pretty-format-json
    args:
      - "--autofix"
- repo: https://github.com/kamadorueda/alejandra
  rev: 4.0.0
  hooks:
  - id: alejandra-system
- repo: https://github.com/astro/deadnix
  rev: v1.3.1
  hooks:
  - id: deadnix
- repo: https://github.com/spinergie/pre-commit-dprint
  rev: 'v0.50.1'  # Use the sha / tag you want to point at
  hooks:
  - id: dprint
    # Ref: https://github.com/spinergie/pre-commit-dprint/issues/1
    args: ['--allow-no-files']
# Disabled due to breaking updates
# TODO: revert to main project when this is merged
# https://github.com/oppiliappan/statix/pull/81
# - repo: https://github.com/Matthieu-LAURENT39/statix/
#   rev: pre-commit
#   hooks:
#   - id: statix-fix
