repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-yaml
    args:
    - "--allow-multiple-documents"
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: check-toml
  - id: check-vcs-permalinks
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: check-json
  - id: pretty-format-json
    args:
      - "--autofix"
- repo: https://github.com/kamadorueda/alejandra
  # TODO: When this issue is resolved, switch to proper tag ref
  # Ref: https://github.com/kamadorueda/alejandra/issues/388
  rev: 9512caae61b6fbda5298a33813976db4f1c0f17d
  hooks:
  - id: alejandra-system
