# helm upgrade --install cilium cilium/cilium --namespace kube-system --values cilium-helm-values.yaml --version 1.17.3
# helm upgrade --install cilium ./cilium-1.17.3.tgz --namespace kube-system --values cilium-helm-values.yaml
# kubectl delete node $(kubectl get nodes | grep NotReady | awk '{print $1;}')
# k delete ciliumnodes --all
# k api-resources | grep -i cilium | cut -d' ' -f1 | xargs -I% kubectl delete % --all
# cat nodes.txt | xargs -I% bash -c 'kubectl annotate node % cilium.io/bgp-virtual-router.65551="router-id=192.168.255.$(shuf -i 0-255 -n 1)" --overwrite'
# kgn -o custom-columns=Node:.metadata.name,Id:".metadata.annotations.cilium\.io/bgp-virtual-router\.65551"

cluster:
  name: kubernetes
# No kube-proxy
kubeProxyReplacement: true
# Enables healthz endpoint
kubeProxyReplacementHealthzBindAddr: "[::]:10256"
# Required to bypass the non-working default APIserver service without kube-proxy
k8sServiceHost: fat-controller.systems.richtman.au
k8sServicePort: 6443
# Set our networking stack
ipv4:
  enabled: false
ipv6:
  enabled: true

# -- Roll out cilium agent pods automatically when configmap is updated.
rollOutCiliumPods: true
l2NeighDiscovery:
  enabled: true

# -- This feature set enables virtual BGP routers to be created via
# CiliumBGPPeeringPolicy CRDs.
bgpControlPlane:
  # -- Enables the BGP control plane.
  enabled: true

# This makes kubectl logs and execs default nicely
podAnnotations:
  kubectl.kubernetes.io/default-container: cilium-agent
enableIPv6BIGTCP: true
enableIPv6Masquerade: true
# Ref: https://docs.cilium.io/en/latest/network/concepts/masquerading/#ebpf-based
bpf:
  # Use BPF instead of iptables masquerading
  # Masquerading is off for anything in the IPv6 native routing CIDR though
  #   which means it's not SNATing pod outbound traffic.
  masquerade: true
  # Allow cluster external access to ClusterIP services.
  lbExternalClusterIP: true
autoDirectNodeRoutes: true
# https://github.com/cilium/cilium/issues/21538
# https://github.com/cilium/cilium/issues/35822
# https://github.com/cilium/cilium/issues/17240
routingMode: native
externalIPs:
  enabled: true
ipv6NativeRoutingCIDR: 2403:580a:e4b1::/48
ipam:
  mode: "cluster-pool" # Should be unnecessary
  operator:
    # Unable to init cluster-pool allocator" error="unable to initialize IPv6 allocator: New CIDR set failed; the node CIDR size is too big" subsys=cilium-operator-generic
    # Ref: https://github.com/cilium/cilium/issues/20756
    clusterPoolIPv6PodCIDRList: ["2403:580a:e4b1::/64"]
    # clusterPoolIPv6PodCIDRList: ["2403:580a:e4b1:1::/64"]
    # Ref: https://github.com/cilium/cilium/issues/20756#issuecomment-2450328186
    clusterPoolIPv6MaskSize: 80

#region Development
envoy:
  enabled: false
# Fully uninstall
# cni:
#   uninstall: true
# debug:
#   enabled: true
operator:
  rolloutPods: true # Should update when configMap changes, not sure if they hot-reload anyway
  replicas: 1
#endregion
