apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: user
spec:
  request: ${KLIENT_CSR}
  signerName: kubernetes.io/kubelet-apiserver-client
  usages:
  - client auth
