apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kanidm-users
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  # name: cluster-admin # for testing
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: k8s_users@id.richtman.au
