apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mytest
  name: mytest
  # namespace: default
spec:
  containers:
  #   args:
  #   - sleep
  #   - "3000"
  - image: docker.io/nginx:latest
    name: mytest
    ports:
    - containerPort: 80
    - containerPort: 8080
    - containerPort: 443
    readinessProbe:
      failureThreshold: 99
      httpGet:
        host: "::1"
        path: /
        port: 80
        scheme: HTTP
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 3
    # volumeMounts:
    # - name: manual-token
    #   mountPath: "/var/run/secrets/kubernetes.io/serviceaccount"
    #   readOnly: true
  dnsPolicy: Default
  restartPolicy: Always
  nodeName: mum.systems.richtman.au
  # automountServiceAccountToken: false
  # volumes:
  # - name: manual-token
  #   projected:
  #     sources:
  #     - serviceAccountToken:
  #         path: "token"
