apiVersion: v1
kind: Pod
metadata:
  labels:
    run: my-test
  name: my-test
spec:
  containers:
  - image: docker.io/nginx:latest
    name: my-test
    ports:
    - containerPort: 80
    readinessProbe:
      httpGet:
        port: 80
      failureThreshold: 99
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeName: patient-zero.systems.richtman.au
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: my-test
  name: mytest-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    run: my-test
  type: ClusterIP
