[Interface]
PrivateKey = <REPLACE>
# Amend for each client to have unique IPs
Address = 10.255.255.2/24, fd64:f161:ae68::2/64
# DNS = 10.128.0.1, 2403:581e:ab78:0:aab8:e0ff:fe00:91ef

[Peer]
PublicKey = <REPLACE>
PresharedKey = <REPLACE>
Endpoint = home.richtman.au:51820
# Split tunnel
AllowedIPs = 10.255.255.0/24, fd60:f161:ae68::/48, 10.128.1.0/24, fd94:d596:9a19::/48
# Full tunnel
#AllowedIPs = 0.0.0.0/0,::/0
