apiVersion: v1
clusters:
- cluster:
    certificate-authority: /var/lib/kubernetes/secrets/k8s-ca.pem
    server: https://fat-controller.systems.richtman.au:6443
  name: local
contexts:
- context:
    cluster: local
    namespace: kube-system
    user: kubelet
  name: local
current-context: local
kind: Config
preferences: {}
users:
- name: kubelet
  user:
    client-certificate: /var/lib/kubernetes/secrets/kubelet-apiserver-client.pem
    client-key: /var/lib/kubernetes/secrets/kubelet-apiserver-client-key.pem
