[defaults]
format = "{time}\n"

[[sessions]]
id = "work"
name = "Work"
duration = "25m"
command = "notify-send 'Work Done!'"

[[sessions]]
id = "rest"
name = "Rest"
duration = "5m"
command = "notify-send 'Rest Done!'"

[[sessions]]
id = "deepwork"
name = "Deep Work"
duration = "50m"
command = "notify-send 'Take 10!'"
