apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oidc-public
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:service-account-issuer-discovery
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:unauthenticated
---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: apiserver
    provider: kubernetes
  name: apiserver-public
  namespace: default
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 6443
  type: LoadBalancer
---
# Think you just have to match the label name...
# Ref: https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
addressType: IPv6
endpoints:
- addresses:
  - 2403:581e:ab78:1:4::a95f
  conditions:
    ready: true
metadata:
  labels:
    kubernetes.io/service-name: apiserver-public
  name: apiserver-public
  namespace: default
ports:
- name: https
  port: 6443
  protocol: TCP
