
theme = "monokai_pro"

[editor]
line-number = "relative"

[editor.file-picker]
hidden = false

[editor.statusline]
center = [ "version-control" ]

[keys.normal]
l = { e = [ "select_mode", "goto_line_end", "normal_mode" ] }

