
theme = "monokai_pro"

[editor]
line-number = "relative"
mouse = false

[editor.lsp]
display-inlay-hints = true

[editor.file-picker]
hidden = false

# Ref: https://www.reddit.com/r/HelixEditor/comments/w3higo/comment/k1okf1g/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
[editor.statusline]
center = [ "version-control" ]

[keys.normal]
l = { e = [ "select_mode", "goto_line_end", "normal_mode" ], b = [ "goto_line_start", "move_next_word_start", "move_char_right" ] }
D = "delete_selection_noyank"

[keys.normal."+"]
c = ":run-shell-command cargo check"
b = ":run-shell-command cargo build"
t = ":run-shell-command cargo test"

# Ref: https://github.com/helix-editor/helix/discussions/6815#discussioncomment-5729582
[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"
