
theme = "monokai_pro"

[editor]
line-number = "relative"

[editor.file-picker]
hidden = false

[editor.statusline]
center = [ "version-control" ]

[keys.normal]
l = { e = [ "select_mode", "goto_line_end", "normal_mode" ], b = [ "goto_line_start", "move_next_word_start", "move_char_right" ] }
D = "delete_selection_noyank"

